name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.14.1
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pip=20.3.3
  - pip:
      - wandb==0.10.31
      - protobuf=3.20.1
      - jinja2=3.0.3